apiVersion: v1
kind: ConfigMap
metadata:
  name: voicevault-config
  namespace: voicevault
data:
  postgres-host: "postgres-service"
  postgres-port: "5432"
  redis-host: "redis-service"
  redis-port: "6379"
  app-port: "3000"
  node-env: "production"