apiVersion: apps/v1
kind: Deployment
metadata:
  name: voicevault
  namespace: voicevault
spec:
  replicas: 3
  selector:
    matchLabels:
      app: voicevault
  template:
    metadata:
      labels:
        app: voicevault
    spec:
      containers:
      - name: voicevault
        image: voicevault:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: voicevault-secrets
              key: database-url
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: regcred 